### ISSUE TITLE
GLOBAL_SENTENCE_BOUNDARY_REGEX fails on certain characters above U+FFFF

### ISSUE THREAD

**Issue by divec** [santhoshtr/sentencex-js#2]
**Steps to reproduce**
1. Create a single sentence with non-BMP characters close in value to a sentence terminator:

```
$ python -c 'print(chr(0x1BC00) * 10)' > 1sentence.txt
```

2. Verify this is really one sentence, using the python version of sentencex:

```
$ python -c 'from sentencex import segment; print(list(segment("en", open("1sentence.txt").read())))'
['𛰀𛰀𛰀𛰀𛰀𛰀𛰀𛰀𛰀𛰀\n']
```
3. Now try with sentencex-js.
```
$ node segment.mjs en < 1sentence.txt
```

**Expected behaviour**
The same output as the python version of sentencex

**Observed behaviour**
```
$ node segment.mjs en < 1sentence.txt
[
  '\ud82f',       '\udc00\ud82f',
  '\udc00\ud82f', '\udc00\ud82f',
  '\udc00\ud82f', '\udc00\ud82f',
  '\udc00\ud82f', '\udc00\ud82f',
  '\udc00\ud82f', '\udc00\ud82f',
  '\udc00\n'
]
```

**Reason**

This happens because Javascript RegExp character classes work in unicode code units. So if a character above U+FFFF appears in a character class, it really means _"match either of the surrogate pairs"_.

**Fix**

Instead of a character class `[foobarbaz]`, we can use a disjunction `(foo|bar|baz)`. But note different escaping rules are needed.

**Comment by divec** [comment]
An alternative would be to build on top of UnicodeJS, and use `unicodeJS.charRangeArrayRegexp` which will build you a disjunction from any character ranges. This might be a good idea because the escaping is quite messy. Essentially, this would fill in the deficiencies in Javascript RegExps compared to python.

It would also give you the Terminator characters direct from the Unicode Character Database so you don't have to maintain terminators.js yourself. Same for close brackets/quotes. For the python version, the "regex" PyPI module exposes much the same Unicode character data (so `regex.split(r'\p{Sentence_Terminal}', 'Hi! मैं यहाँ हूँ।歡迎。')` returns `['Hi', ' मैं यहाँ हूँ', '歡迎', '']`). So the two versions could still develop in parallel.

If you think building on UnicodeJS is a good idea, we should restructure UnicodeJS to support module import.

**Comment by divec** [comment]
I noticed terminators.js has some wrong data (e.g. it includes some Amharic letters), so I went ahead and wrote an example patchset that uses unicodejs data instead.

**Comment by santhoshtr** [comment]
@divec I used the `u` flag of js Regex to handle the issue of characters above U+FFFF and that makes the test you added passing.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode

Any reason why the native `u` flag was not considered for unicodejs?

**Comment by divec** [comment]
Thanks @santhoshtr, yes indeed `/u` is an alternative fix for this issue.

UnicodeJS's `charRangeArrayRegexp` method predates the native `/u` flag by 3 years or so ... it's still useful for ensuring correctness: it helps avoid escaping mistakes when constructing a RegExp from a data source of character ranges. For example if you some day will build `parensRegex` from the Unicode Character Database, it will help ensure a `]` in the data does not mistakenly close a character class. The performance is similar.
